name: project testing

on:
  push:
    branches:
      - main
    paths:
      - project/**


jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Kaggle API
        run: |
          mkdir ~/.kaggle
          echo "$KAGGLE_USERNAME:$KAGGLE_KEY" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: List Directory 
        run: |
          ls
      # execute test pipeline
      - name: Run shell script
        run: |
          chmod +x ./project/tests.sh &&  sh ./project/tests.sh
