name: project testing

on:
  push:
    branches:
      - main
    paths:
      - project/**
env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: List Directory 
        run: |
          cd project && ls
      # execute test pipeline
      - name: Run shell script
        run: |
          sudo chmod +x ./project/tests.sh 
          cd ./project 
          sudo ./tests.sh
