name: Project Testing

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get Directory
        run: |
          ls
      # Run exercise feedback
      - name: Project Testing
        run: sh /project/tests.sh
